(() => {
  "use strict";

  const subject = (paperCode, subjectName, marks = "", details = {}) => ({
    paperCode,
    subjectName,
    marks,
    options: [],
    ...details,
  });

  const semester = (semesterNumber, subjects) => ({ semesterNumber, subjects });

  window.RKAC_PROGRAMMES = [
    {
      id: "bcom",
      title: "Bachelor of Commerce",
      shortName: "B.Com",
      description: "Bachelor of Commerce is a 3-year undergraduate degree in Commerce, with focus on Economics, Business Management, accounting principles, export and import laws, economic policies, trade and business management.",
      courseName: "Bachelor of Commerce (B.Com) Regular",
      duration: "3 years (Semester System)",
      eligibility: "10+2 with at least 40% marks in aggregate in any stream or equivalent examination.",
      seats: "1 Unit (75 Seats)",
      careers: ["Banking sector", "Accountant", "Insurance", "Entrepreneur", "Tax Consultant", "C.A. / C.S.I. / I.C.W.A.I. / M.B.A.", "Post Graduation in the related subject", "Eligible for UPSC, CDS Exams", "Jobs in Banking Sector"],
      outcomes: ["Academic Excellence", "Professional Excellence", "Effective Communication", "Ethics", "Social Interaction", "Critical Thinking"],
      semesters: [
        semester(1, [subject("BCG-101", "English (Compulsory)", 50), subject("BCG-102", "Punjabi Compulsory", 50), subject("BCG-103", "Financial Accounting", 50), subject("BCG-104", "Business Organisation", 50), subject("BCG-105", "Business Communication", 50), subject("BCG-106", "Business Statistics", 50), subject("BCG-107", "Computer Fundamentals", 50), subject("", "Drug Abuse: Problem, Management and Prevention (Compulsory)", 50, { note: "Drug Abuse marks are not included in Total Marks." })]),
        semester(2, [subject("BCG-201", "English (Compulsory)", 50), subject("BCG-202", "English (Compulsory)", 50), subject("BCG-203", "Advanced Financial Accounting", 50), subject("BCG-204", "Commercial Laws", 50), subject("BCG-205", "Business Economics", 50), subject("BCG-206", "Functional Management", 50), subject("BCG-207", "Seminar", 50), subject("", "Drug Abuse: Problem, Management and Prevention (Compulsory)", 50, { note: "Drug Abuse marks are not included in Total Marks." })]),
        semester(3, [subject("BCG-301", "English (Compulsory)", 50), subject("BCG-302", "Punjabi Compulsory", 50), subject("BCG-303", "Corporate Accounting", 50), subject("BCG-304", "Company Law", 50), subject("BCG-305", "Financial Management", 50), subject("BCG-306", "International Business", 50), subject("BCG-307", "Business Environment", 50), subject("ESL-221", "Environmental Studies-I", 50)]),
        semester(4, [subject("BCG-401", "English (Compulsory)", 50), subject("BCG-402", "Punjabi Compulsory", 50), subject("BCG-403", "Goods and Services Tax (GST)", 50), subject("BCG-404", "Industrial Laws", 50), subject("BCG-405", "Principles and Practices of Banking and Insurance", 50), subject("BCG-406", "Cost Accounting", 50), subject("ESL-222", "Environmental Studies-II", 50), subject("BCG-407", "Seminar", 50)]),
        semester(5, [subject("BCG-501", "English (Compulsory)", 50), subject("BCG-501", "Punjabi Compulsory", 50), subject("BCG-501", "Management Accounting", 50), subject("BCG-501", "Cost Accounting", 50), subject("BCG-501", "Operations Research", 50), subject("BCG-501", "Specialization Course 1", 50), subject("", "Specialization Course 2", 50)]),
        semester(6, [subject("BCG-601", "English (Compulsory)", 50), subject("BCG-601", "Punjabi Compulsory", 50), subject("BCG-601", "Auditing", 50), subject("BCG-601", "Direct Tax Laws", 50), subject("BCG-601", "Corporate Governance", 50), subject("BCG-601", "Specialization Course 1", 50), subject("BCG-601", "Specialization Course 2", 50)]),
      ],
    },
    {
      id: "mcom", title: "Master of Commerce", shortName: "M.Com", description: "A 2-year degree course in 4 semesters, focusing on advanced HRM, Business Studies, Marketing Management, Financial Management, Managerial Economics, Accounting and Auditing, Business Ethics, Accounting through IT and related areas.", courseName: "Masters in Commerce (M.Com)", duration: "2 years (Semester System)", eligibility: "B.Com / BBA / B.CAM / B.E. Commerce with at least 50% marks in aggregate or equivalent examination.", seats: "1 Unit (60 Seats)", careers: ["Accountants", "Research Associates", "Tax Advisors", "Financial Services", "Finance Managers", "Corporate Sector"], outcomes: ["Academic Excellence", "Professional Excellence", "Effective Communication", "Ethics", "Social Interaction", "Critical Thinking", "Research Aptitude"],
      semesters: [
        semester(1, [subject("MC-101", "Managerial Economics"), subject("MC-102", "Statistical Analysis for Business", 75), subject("MC-103", "Management Principles and Organization Behaviour", 75), subject("MC-104", "Business Environment", 50), subject("MC-105", "Management Accounting and Control Systems", 50), subject("MC-106", "Seminar", 75)]),
        semester(2, [subject("MC-201", "Corporate Financial Accounting", 75), subject("MC-202", "Financial Management", 75), subject("MC-203", "Research Methodology", 75), subject("MC-204", "Marketing and Human Resource", 50), subject("MC-205", "Computer Application in Business", 50), subject("MC-206", "Viva voce", 75)]),
        semester(3, [subject("MC-301", "Banking and Insurance Services", 75), subject("MC-302", "Seminar", 75), subject("", "Group A: Accounting and Finance", 75), subject("MC-311", "Security Analysis and Portfolio Management", 50), subject("MC-312", "Contemporary Accounting", 50), subject("", "Group D: Marketing", 25), subject("MC-351", "Consumer Behaviour"), subject("MC-352", "Research for Marketing Decisions")]),
        semester(4, [subject("MC-401", "International Accounting", 75), subject("MC-402", "Corporate e-Reporting", 75), subject("MC-403", "Viva voce", 75), subject("", "Group A: Accounting and Finance", 75), subject("MC-411", "International Financial Management", 50), subject("MC-412", "Financial Markets and Financial Services", 50), subject("MC-413", "Corporate Tax Law and Planning", 50)]),
      ],
    },
    {
      id: "bca", title: "Bachelor of Computer Applications", shortName: "BCA", description: "BCA is a 3-year undergraduate degree course in computer applications, divided into 6 semesters. The programme covers database, networking, data structures and programming languages such as C and Java.", courseName: "Bachelor in Computer Application (BCA)", duration: "3 years (Semester System)", eligibility: "+2 with at least 40% marks in aggregate or equivalent examination.", seats: "60", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "Jobs in Banking Sector", "Software Engineer", "Project Manager", "Web Administrator", "DBA", "System Administrator", "Software Developer", "Network Administrator", "CCNA", "MCSE", "Ethical Hacking", "Data Analyst", "Cyber Security", "OCP", "M.Sc. I.T./C.S.", "M.S.", "M.C.A.", "M.B.A."], outcomes: ["Computer literacy and understanding of operating systems", "Ability to organize and present work using software", "Use of software in academic and professional environments", "Effective presentations and communication", "IT-oriented security and protocols", "Web-page design and implementation", "Technical support and business management", "System administration and DBMS knowledge"],
      semesters: [
        semester(1, [subject("Paper-I", "Introduction to Programming - C", 75), subject("Paper-II", "Introduction to Computers and Information Technology", 75), subject("Paper-III", "Applied & Discrete Mathematics", 75), subject("Paper-IV", "Communication Skills in English - I", 50), subject("Paper-V", "Punjabi / mu`FlI pMjwbI (Compulsory)", 50), subject("Paper-VI", "Practical-I (MS Office 2010 and Basic C Programming)", 75), subject("Paper-VII", "Drug Abuse: Problem, Management and Prevention", 50)]),
        semester(2, [subject("Paper-I", "Introduction to Programming - C++", 75), subject("Paper-II", "Principles of Digital Electronics", 75), subject("Paper-III", "Numerical Methods & Statistical Techniques", 75), subject("Paper-IV", "Communication Skills in English - II (Th.35+Pr.15)", 50), subject("Paper-V", "Punjabi / mu`FlI pMjwbI (Compulsory)", 50), subject("Paper-VI", "Practical-I (Advanced C Programming)", 75), subject("Paper-VII", "Drug Abuse: Problem, Management and Prevention", 50)]),
        semester(3, [subject("Paper-I", "Computer Architecture", 75), subject("Paper-II", "Database Management System", 75), subject("Paper-III", "Computational Problem Solving Using Python", 75), subject("Paper-IV", "Environmental Studies - I", 50), subject("Paper-V", "Programming Lab - C++", 50), subject("Paper-VI", "Programming Lab - Oracle", 25)]),
        semester(4, [subject("Paper-I", "Data Structure & File Processing", 75), subject("Paper-II", "Information Systems", 75), subject("Paper-III", "Internet Applications", 75), subject("Paper-IV", "System Software", 75), subject("Paper-V", "Environmental Studies - II", 50), subject("Paper-VII", "Lab - Data Structures Implementation using C++", 50), subject("Paper-VII", "Lab - Web Designing and use of Internet", 50)]),
        semester(5, [subject("Paper-I", "Computer Networks", 75), subject("Paper-II", "Web Technologies", 75), subject("Paper-III", "Operating System", 75), subject("Paper-IV", "JAVA Programming Language", 75), subject("Paper-V", "Lab based on JAVA Programming Language", 50), subject("Paper-VI", "Lab based on ASP.NET", 50)]),
        semester(6, [subject("Paper-I", "Computer Graphics", 75), subject("Paper-II", "Software Engineering", 75), subject("Paper-III", "Lab. Implementation of Applications of Computer Graphics in C++/C", 50), subject("Paper-IV", "Project", 200)]),
      ],
    },
    {
      id: "bsc-it", title: "Bachelor of Science (Information Technology)", shortName: "B.Sc.(I.T.)", description: "A 3-year undergraduate degree course divided into 6 semesters. The programme covers databases, networking, data structures, programming, web technologies and related IT subjects.", courseName: "Bachelor of Science (Information Technology) B.Sc(I.T.)", duration: "3 years (Semester System)", eligibility: "+2 with at least 40% marks in aggregate or equivalent examination.", seats: "60", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "Jobs in Banking Sector", "Software Engineer", "Project Manager", "Web Administrator", "DBA", "System Administrator", "Software Developer", "Network Administrator", "CCNA", "MCSE", "Ethical Hacking", "Data Analyst", "Cyber Security", "OCP", "M.Sc. I.T./C.S.", "M.S.", "M.C.A.", "M.B.A."], outcomes: ["Communicate computer science concepts effectively", "Apply computing knowledge to specific problems", "Analyse scholarly literature", "Use software development tools and computing platforms", "Work collaboratively on computing projects", "Plan and execute small-scale research projects", "Advance knowledge through innovation", "Pursue lifelong learning", "Interpret and present theoretical and empirical findings"],
      semesters: [
        semester(1, [subject("Paper-1", "Introduction to Programming - C", 75), subject("Paper-2", "Introduction to Computers and Information Technology", 75), subject("Paper-3", "Applied & Discrete Mathematics", 75), subject("Paper-4", "Communication Skills in English - I", 50), subject("Paper-5", "Punjabi / mu`FlI pMjwbI (Compulsory)", 50), subject("Paper-6", "Practical - PC Computing & C Language-I", 75), subject("Paper-7", "Drug Abuse: Problem, Management and Prevention", 50)]),
        semester(2, [subject("Paper-1", "Communication Skills in English - II (Th.35+Pr.15)", 50), subject("Paper-2", "Punjabi / mu`FlI pMjwbI (Compulsory)", 50), subject("Paper-3", "Principles of Digital Electronics", 75), subject("Paper-4", "Introduction to Programming - C++", 75), subject("Paper-5", "Numerical Methods & Statistical Techniques", 75), subject("Paper-6", "Practical - C Language - II", 75), subject("Paper-7", "Drug Abuse: Problem, Management and Prevention", 50)]),
        semester(3, [subject("Paper-1", "Introduction to Python", 75), subject("Paper-2", "Data Structure", 75), subject("Paper-3", "System Analysis & Design", 75), subject("Paper-4", "Environmental Studies - I", 50), subject("Paper-5", "Programming Lab - I (C++, Programming Language)", 50), subject("Paper-6", "Programming Lab - II (Data Structure)", 25)]),
        semester(4, [subject("Paper-1", "Database Management System", 75), subject("Paper-2", "Internet Applications", 75), subject("Paper-3", "JAVA & Web Designing", 75), subject("Paper-4", "Environmental Studies - II", 50), subject("Paper-5", "Web Technologies", 75), subject("Paper-6", "Programming Lab - I (Oracle)", 50), subject("Paper-7", "Programming Lab - II HTML & (JAVA)", 50)]),
        semester(5, [subject("Paper-1", "Computer Networks", 100), subject("Paper-2", "Operating System", 100), subject("Paper-3", "E-Business", 100), subject("Paper-4", "Lab - I (Computer Networks)", 50), subject("Paper-5", "Lab - II (Operating System)", 50)]),
        semester(6, [subject("Paper-1", "Computer Graphics", 75), subject("Paper-2", "Applications of Computer Graphics in C++/C", 25), subject("Paper-3", "Project", 300)]),
      ],
    },
    {
      id: "pgdca", title: "P.G. Diploma in Computer Applications", shortName: "PGDCA", description: "A 1-year diploma course in 2 semesters covering PC Computing, Scripting Language, Web Designing, Internet, DBMS through Oracle, System Analysis & Design, Network Concepts, Programming in C, Computer Fundamentals, Operating Systems and E-Commerce.", courseName: "PGDCA", duration: "1 year (Semester System)", eligibility: "Graduation in any stream with 45% marks in aggregate or equivalent examination.", seats: "2 Units (80 Seats)", careers: ["DTP Manager", "Clerk cum Junior Data Entry Operator", "Junior Technician", "Computer Network and Hardware Troubleshooting"], outcomes: ["Application development skills", "Knowledge of latest computer and IT trends", "Understanding of data and resource protection", "Computer software security knowledge", "Real-life IT application development", "Basic computer technology and IT applications", "Design and develop applications for computer science problems"],
      semesters: [
        semester(1, [subject("Paper-I", "PC Computing-I (MS Office) 2003", "", { theory: 50, practical: 50 }), subject("Paper-II", "PC Computing-II (Professional DTP)", "", { theory: 50, practical: 50 }), subject("Paper-III", "Fundamentals of Computer & Operating Systems", "", { theory: 50, practical: 50 }), subject("Paper-IV", "Database Management System through Oracle-10g & System Analysis & Design", "", { theory: 50, practical: 50 })]),
        semester(2, [subject("Paper-I", "Network Concepts and Management (Hardware, Software, setting in LINUX/UNIX/NT environment)", "", { theory: 50, practical: 50 }), subject("Paper-II", "Programming in C", "", { theory: 50, practical: 50 }), subject("Paper-III", "Introduction to Scripting Languages, Web Designing & Uses of Internet", "", { theory: 50, practical: 50 }), subject("Paper-IV", "E-Commerce / Business", "", { theory: 50, practical: 50 })]),
      ],
    },
    {
      id: "cca", title: "Certificate of Computer Applications", shortName: "CCA", description: "A 1-year diploma course focused on computer applications, practical knowledge and technical skills used in everyday life.", courseName: "CCA", duration: "1 year (Semester System)", eligibility: "+2 examination with at least 40% marks in aggregate or equivalent examination.", seats: "1 Unit (50 Seats)", mainAreas: ["Basic Computer Skills", "MS Office Applications", "Internet Basics", "E-Business", "Software Hacking & IT Security", "PC Assembly and Troubleshooting"], careers: ["Database Developer", "Clerk cum Junior Data Entry Operator", "Junior Technician", "Computer Hardware Troubleshooting"], outcomes: ["Animation project planning and implementation", "Animation sequencing", "Cinematography principles", "Storytelling skills", "Performance theory", "Layout and background design", "Visual concept presentation", "Digital asset management"], semesters: [semester(1, [subject("Paper-I", "Information Technology and Operating System", "", { theory: 50, practical: 50 }), subject("Paper-II", "PC Computing-I", "", { theory: 50, practical: 50 })]), semester(2, [subject("Paper-I", "Database Management System", "", { theory: 50, practical: 50 }), subject("Paper-II", "PC Computing-II", "", { theory: 50, practical: 50 })])],
    },
    {
      id: "msc-cs", title: "Master of Science (Computer Science)", shortName: "M.Sc. Computer Science", description: "A 2-year postgraduate programme covering advanced computing, programming, DBMS, networking, web technology, image processing, algorithm analysis, soft computing, website development and related areas.", courseName: "M. Sc. (Computer Science)", duration: "2 Years (Semester System)", eligibility: "Graduate with Computer Science / IT / Computer Applications / Computer Maintenance as one elective subject with 50% marks; BCA / B.Sc. (IT) / BIT or equivalent with at least 50% marks; or Graduate with Mathematics as an elective subject plus PG Diploma in Computer Applications / Information Technology / E-Commerce / Internet Application or equivalent with 50% marks.", seats: "1 Unit (30 seats each)", careers: ["Web Designing Specialist", "Project Manager", "DTP Managers and Administrators", "Career in Computer Education", "System Integrator", "MIS Director", "M.Tech. (IT / Computer Science)"], outcomes: ["Professional communication of computer science concepts", "Computing-based problem solving", "Scholarly literature analysis", "Software development tools and computing platforms", "Collaborative work and project management", "Small-scale research", "Innovation and knowledge creation", "Lifelong learning", "Interpretation and presentation of theoretical and empirical findings"],
      semesters: [semester(1, [subject("MCS-101", "Advanced Data Structures"), subject("MCS-102", "Advanced Computer Architecture"), subject("MCS-103", "Network Design & Performance Analysis"), subject("MCS-104", "Discrete Structures"), subject("MCS-105", "Soft Computing"), subject("MCS-106P", "Programming Laboratory - I")]), semester(2, [subject("MCS-201", "Theory of Computation"), subject("MCS-202", "Image Processing"), subject("MCS-203", "Design & Analysis of Algorithms"), subject("MCS-204", "Cloud Computing"), subject("MCS-205", "Distributed Database Systems"), subject("MCS-206P", "Programming Laboratory - II")]), semester(3, [subject("MCS-301", "Advanced Software Engineering"), subject("MCS-302", "System Software"), subject("MCS-303", "Data Mining and Warehousing"), subject("MCS-304", "Concept of Core and Advanced Java"), subject("MCS-305", "Network Programming"), subject("MCS-306P", "Programming Laboratory - III (Based on Advanced Java and Network Programming)")]), semester(4, [subject("MCS-401", "Advanced Web Technologies using ASP.NET", 100), subject("MCS-402", "Microprocessor and Its Applications", 100), subject("MCS-403", "Object Oriented Modeling, Analysis and Design", 100), subject("MCS-404P", "Programming Laboratory - IV (Based on Advanced Web Technologies using ASP.NET)", 100), subject("MCS-405P", "Project Work", 200)])],
    },
    {
      id: "ba", title: "Bachelor of Arts", shortName: "B.A.", description: "The college offers multiple combinations of subjects so students can pursue areas of interest. The programme is supported by qualified faculty and includes humanities-oriented study.", duration: "3 years (Semester System)", eligibility: "+2 with at least 40% marks in aggregate or equivalent examination.", seats: "250", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "Data Entry Operator", "B.Ed.", "Post graduation in related subjects", "M.C.A.", "M.B.A.", "L.L.B."], outcomeAreas: ["Punjabi", "English", "Geography", "Hindi", "History", "Punjabi (Elective)", "Political Science", "Computer Application", "Physical Education"], compulsorySubjects: ["General English", "General Punjabi", "Drug Abuse: Problem, Management and Prevention (Sem-I & II)", "Environmental Studies (Sem-III)"], electives: ["Economics or Physical Education", "History or Mathematics", "Geography", "Elective Punjabi or Elective Hindi", "Political Science or Mathematics", "Physical Education or Computer Application", "Mathematics or Physical Education"], note: "Students must select any three elective subjects." 
    },
    {
      id: "ma-history", title: "Master of Arts (History)", shortName: "M.A. History", description: "The Department of History was established in 1952. The Master of Arts in History course started in 2005-06. The department has organised UGC-sponsored international and national seminars.", courseName: "Master of Arts (History)", duration: "2 years (Semester System)", eligibility: "Bachelor of Arts (Honours) in any subject or Bachelor of Social Sciences (Honours School); B.A. in any subject with at least 50% marks in aggregate (45% for SC/ST); B.A. in any subject with at least 45% marks in History/Sociology/Public Administration (40% for SC/ST); or any other examination recognized as equivalent.", seats: "40", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "Jobs in Banking Sector"], outcomes: ["Understanding historical events, chronology, personalities and turning points", "Critical analysis of competing interpretations", "Multi-causal explanations of historical developments", "Evaluation of historical ideas and arguments", "Construction of original historical arguments", "Historical research skills", "Effective use of libraries, archives and databases"],
      semesters: [semester(1, [subject("Paper-1", "Political Processes and Structures in India upto A.D. 1200", 80), subject("Paper-2", "Option A: Society and Culture in India upto A.D.1200; Option B: Polity and Economy of India (A.D. 1200-1526)", 80), subject("Paper-3", "Polity and Economy of India (A.D.1526-1750)", 80), subject("Paper-4", "Political Ideas and Institutions in India (A.D.1757-1947)", 80), subject("Paper-5", "History of the Punjab (A.D.1450-1708)", 80)]), semester(2, [subject("Paper-1", "Urban and Agrarian Economy in India upto A.D. 1200", 80), subject("Paper-2", "Option A: Society and Culture of India (A.D. 1200-1750); Option B: Art, Architecture and Literature (A.D.1200-1750)", 80), subject("Paper-3", "Option A: Eighteenth Century Punjab; Option B: Polity, Economy and Society in the Punjab (A.D.1799-1849)", 80), subject("Paper-4", "Modern World: Major Trends (A.D.1500-1900)", 80), subject("Paper-5", "Economic History of Modern India (A.D.1757-1857)", 80)]), semester(3, [subject("Paper-1", "Option A: Socio-Cultural History of India (A.D.1757-1857); Option B: Socio-Cultural History of India (A.D.1858-1947)", 80), subject("Paper-2", "Emergence of Indian Nationalism (A.D.1857-1919)", 80), subject("Paper-3", "Punjab under Colonial Rule (A.D.1849-1947)", 80), subject("Paper-4", "Twentieth Century World (A.D.1901-2000)", 80), subject("Paper-5", "Historical Thought and Historiography", 80)]), semester(4, [subject("Paper-1", "Economic History of Modern India (A.D. 1858-1947)", 80), subject("Paper-2", "The National Movement (A.D.1920-1947)", 80), subject("Paper-3", "Option A: Contemporary India (A.D.1947-2013); Option B: Contemporary Punjab", 80), subject("Paper-4", "Indian Historiography", 80), subject("Paper-5", "Option A: History of Ideas; Option B: Science and Technology: Colonial India; Option C: Women in Modern India (A.D.1858-1947)", 80)])],
    },
    {
      id: "bsc-non-medical", title: "Bachelor of Science (Non Medical)", shortName: "B.Sc. Non Medical", description: "The programme provides theoretical and practical knowledge in science fields including Physics, Chemistry and Mathematics.", duration: "3 years (6 semesters)", eligibility: "+2 (Non Medical) with at least 40% marks in aggregate or equivalent examination.", seats: "60", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "Pharmaceutical company", "Various streams of engineering", "B.Ed.", "Post graduation in related subjects", "M.C.A.", "M.B.A.", "L.L.B."], outcomes: ["Scientific attitude and experimental skills", "Data analysis and measurement", "Scientific theories and applications", "Physics", "Chemistry", "Mathematics", "Critical thinking and independent problem solving", "Laboratory and experimental techniques"], subjectsOffered: ["General English", "General Punjabi", "Physics", "Chemistry", "Mathematics", "Drug Abuse: Problem, Management and Prevention (Sem-I & II)", "Environmental Studies (Sem-III)"]
    },
    {
      id: "bsc-cs", title: "Bachelor of Science (Computer Science)", shortName: "B.Sc. Computer Science", description: "A 3-year undergraduate programme providing theoretical and practical knowledge in Computer Science, Mathematics and related scientific areas.", duration: "3 years (6 semesters)", eligibility: "+2 (Non Medical) with at least 40% marks in aggregate or equivalent examination.", seats: "60", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "Data Entry Operator", "B.Ed.", "Post graduation in related subjects", "M.C.A.", "M.B.A.", "L.L.B."], outcomes: ["Organize information using appropriate software", "Effective presentation and communication", "Systems Analysis and Design", "Programming, networking, database and web design", "Teamwork and professional behaviour", "IT security and protocols", "Web-page design", "Technical support", "DBMS and system administration"], subjectsOffered: ["General English", "General Punjabi", "Computer Science", "Physics", "Mathematics", "Drug Abuse: Problem, Management and Prevention (Sem-I & II)", "Environmental Studies (Sem-III)"]
    },
    {
      id: "bsc-economics", title: "Bachelor of Science (Economics)", shortName: "B.Sc. Economics", description: "A 3-year undergraduate programme combining Economics, Computer Science and Mathematics.", duration: "3 years (6 semesters)", eligibility: "+2 (With Mathematics) with at least 40% marks in aggregate or equivalent examination.", seats: "60", careers: ["Jobs in Government Sector", "Eligible for UPSC, CDS Exams", "B.Ed.", "Post graduation in related subjects", "M.C.A.", "M.B.A.", "L.L.B."], outcomes: ["Communication of findings", "Explanation of complex data", "Awareness of global historical and institutional forces", "Understanding ethical values in decision making", "Conceptual models of behaviour", "Understanding policy and market changes", "Applying economic reasoning to everyday decisions"], subjectsOffered: ["General English", "General Punjabi", "Economics", "Computer Science", "Mathematics", "Drug Abuse: Problem, Management and Prevention (Sem-I & II)", "Environmental Studies (Sem-III)"]
    }
  ];
})();
